Fix missing typing-extensions dependency
Running the following in a clean virtualenv:
```
pip install flake8 flake8_class_attributes_order
flake8
```

Results in an error like the following:
```
File ".../lib/python3.6/site-packages/flake8_class_attributes_order/checker.py", line 4, in <module>
  from typing_extensions import Final
ModuleNotFoundError: No module named 'typing_extensions'
```

This change adds `flake8` and `typing-extensions` as requirements for
this package, fixing this error.